services:
  postgres:
    image: postgres:17-alpine
    container_name: sistema-cobranza-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deudas_db
    ports:
      - "5432:5432"
    volumes:
      - ./estructura_deudas_db.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d deudas_db"]
      interval: 5s
      timeout: 5s
      retries: 5
